server:
  port: 8081
  error:
    path: /error

spring:
  main:
    web-application-type: reactive
  application:
    name: sandbox
  mvc:
    log-resolved-exception: false
    locale: zh_CN
  jackson:
    serialization:
      write-dates-as-timestamps: true

sandbox:
  work-dir: "D:\\Download\\sandbox-java"
  runner-jar-path: "D:\\Doc\\GitRepo\\sandbox-java\\runner\\target\\runner-0.0.1-SNAPSHOT.jar"
  runner-timeout-seconds: 5
  runner-jvm-options:
    - "-XX:+UseConcMarkSweepGC"
    - "-Xms4m"
    - "-Xmx4m"
    - "-Xmn3m"
    - "-Xss1m"
    - "-XX:SurvivorRatio=1"
    - "-XX:+DisableExplicitGC"
    - "-Xnoclassgc"


